# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# ---------- API Gateway ----------
- task: Maven@3
  displayName: 'Build API Gateway'
  inputs:
    mavenPomFile: 'OnlineLearningPlatformApiGatewayCb/pom.xml'
    goals: 'clean package'

# ---------- Config Server ----------
- task: Maven@3
  displayName: 'Build Config Server'
  inputs:
    mavenPomFile: 'OnlineLearningPlatformConfigServer/pom.xml'
    goals: 'clean package'

# ---------- Courses Service ----------
- task: Maven@3
  displayName: 'Build Courses Service'
  inputs:
    mavenPomFile: 'OnlineLearningPlatformCourses/pom.xml'
    goals: 'clean package'

# ---------- Eureka Server ----------
- task: Maven@3
  displayName: 'Build Eureka Server'
  inputs:
    mavenPomFile: 'OnlineLearningPlatformEurekaServer/pom.xml'
    goals: 'clean package'

# ---------- OnlinelearningPlatform (Fix: lowercase L!) ----------
- task: Maven@3
  displayName: 'Build Main OnlinelearningPlatform'
  inputs:
    mavenPomFile: 'OnlinelearningPlatform/pom.xml'
    goals: 'clean package'